print("hello world")
print("hello world")
print("hello world")

import random
print(random.randint(3,10))
print(random.randint(3,10))
print(random.randint(3,10))
print(random.randint(3,10))
print(random.randint(3,10))
print(random.randint(3,10))
print(random.randint(3,10))
print(random.randint(3,10))
print(random.randint(3,10))
print(random.randint(3,10))
print(random.randint(3,10))